name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag g-spider:$(date +%s)
  list:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: docker images
  login:
    needs: list
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker login --username=g453030291 registry.cn-hangzhou.aliyuncs.com
          g453030291
#
#      run: docker tag [ImageId] registry.cn-hangzhou.aliyuncs.com/g-argo/g-repo-argo:[镜像版本号]
#      run: docker push registry.cn-hangzhou.aliyuncs.com/g-argo/g-repo-argo:[镜像版本号]